version: 0.2

phases:
  install:
    commands:
      - sudo yum install pip -y
      - pip install flask
      - pip install requests
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - main.py
    - test_app.py
    - appspec.yml
    - templates/home.html
    - templates/about.html
    - templates/template.html
    - static/template.css
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask.sh